project:
  type: default
  render: ["index.qmd"]
  output-dir: _site
  resources:
    - assets/vendor/

filters:
  - webr

webr:
  packages: ['tibble']
  show-startup-message: false
  autoload-packages: true

format:
  revealjs:
    theme: [default, assets/theme.scss]
    slide-number: c/t
    revealjs-plugins:
      - drop
    progress: true
    controls: true
    controls-layout: edges
    controls-back-arrows: visible
    navigation-mode: linear
    footer: "[gcabrerag.rbind.io](https://gcabrerag.rbind.io)"
    transition: fade
    transition-speed: fast
    history: true
    chalkboard:
      buttons: true
    menu:
      side: left
      numbers: true
    include-in-header:
      - file: assets/head.html
    include-after-body:
      - file: assets/animations.html
      - file: assets/js/mutate-anim.html
      - file: assets/js/filter-demo.html
      - file: assets/js/pivot-longer-anim.html
      - file: assets/js/pivot-wider-anim.html
      - file: assets/js/ggplot-anim.html
      - file: assets/js/ohlc-data.html
      - file: assets/js/first-plot-anim.html
      - file: assets/js/matrix-anim.html
    code-line-numbers: false
    code-copy: false
    highlight-style: assets/syntax.theme

execute:
  echo: true
  warning: false
  message: false
  freeze: auto

knitr:
  opts_chunk:
    dev: "svg"
    fig.width: 7
    fig.height: 4.2
    fig.align: "center"
