---
title: "Seminar 2"
subtitle: "Describing Data 2 (Descriptive Statistics)"
thanks: "gabriel.cabreraguzman@postgrad.manchester.ac.uk"
author: 
    - name: Gabriel E. Cabrera Guzmán
      orcid: 0000-0000-0000-0000
short-author: "Gabriel E. Cabrera Guzmán"
institute: | 
     | The University of Manchester
     | Alliance Manchester Business School
date: "today"
date-format: long
format:
  beamer:
      navigation: horizontal
      theme: default
      colortheme: default
      aspectratio: 43
include-in-header: 
    - before-body.tex
template-partials:
  - title.tex
keep-tex: true
---

## Exercise 1

The following information on car ownership was collected in a survey of households conducted by the Traffic Department of a town council. Calculate the mean, median, and mode, as well as the variance and standard deviation of the car ownership of these households. \vspace{10pt}

| Number of Cars per Household | Number of Households |
|:----------------------------:|:--------------------:|
| 0                            | 300                  |
| 1                            | 420                  |
| 2                            | 180                  |
| 3                            | 60                   |
| 4                            | 40                   |

## Exercise 1 (Cont'd)

**A**: Number of cars per household is a discrete variable, meaning that it takes values such as 0, 1, 2, 3, etc. (the data can only take integer values). Note that the total number of observations is the sum of frequencies, which is 300 + 420 + 180 + 60 + 40 = 1000. Therefore, we have: 

\vspace{-10pt}
$$
\begin{aligned}
Mean        & = \bar{X} = \frac{\sum^{s}_{j=1}X_j \times F_j}{n} \\
            & = \frac{0 \times 300 + 1 \times 420 + 2 \times 180 + 3 \times 60 + 4 \times 40}{1000} \\
            & = \frac{1120}{1000} = 1.12
\end{aligned}
$$

## 

Regarding the median, note that there are 1000 of data points, so the median will be the average of the values for observation 500th and 501st. Given there are 300 households with 0 car and 420 households with one car, the observations 500th and 500th lie in the second bin and they have one car. Hence, their average is 1, which means the median is also 1.  

Finally, the mode is also 1, since it appears 420 times, which is more than any other numbers. 

## 

For variance, we first use a typical method that is more time-consuming. We need to calculate the squared of deviation times the corresponding frequency for each row as follows: \vspace{6pt} 

```{=latex}
\begin{table}
\centering
\scriptsize
\resizebox{1\textwidth}{!}{
\begin{tabular}{cccc}
\toprule
\textbf{Number of Cars ($X_j$)} & \textbf{Households ($F_j$)} & \textbf{($X_j - \bar{X}$)$^2$} & \textbf{($X_j - \bar{X}$)$^2 \times F_j$} \\
\midrule
0 & 300 & $(0 - 1.12)^2 = 1.2544$ & $1.2544 \times 300 = 376.32$ \\
1 & 420 & $(1 - 1.12)^2 = 0.0144$ & $0.0144 \times 420 = 6.048$ \\
2 & 180 & $(2 - 1.12)^2 = 0.7744$ & $0.7744 \times 180 = 139.392$ \\
3 &  60 & $(3 - 1.12)^2 = 3.5344$ & $3.5344 \times 60 = 212.064$ \\
4 &  40 & $(4 - 1.12)^2 = 8.2944$ & $8.2944 \times 40 = 331.776$ \\
\midrule
\textbf{Total} & \textbf{1000} &  & \textbf{1065.6} \\
\bottomrule
\end{tabular}
}
\end{table}
```
\vspace{10pt} 
 
* $Variance(X) = S^2 = \frac{\sum^{5}_{j=1}(X_j - \bar{X})^2 \times F_j}{n - 1} = \frac{1065.6}{999} = 1.066$

* $Standard \; Deviation(X) = S = \sqrt{1.066} = 1.032$

## 

Let us explore an easier method. We want to use relative frequencies and the formula:

\vspace{-5pt}
$$
Variance(X) = E(X^2) - \mu^2
$$

\vspace{-5pt}
```{=latex}
\begin{table}
\centering
\scriptsize
\resizebox{1\textwidth}{!}{
\begin{tabular}{cccc}
\toprule
\textbf{Number of Cars per Household} & \textbf{Relative Frequency} & $(X_j)^2$ & $(X_j)^2 \times f_j$ \\
\midrule
0 & 0.30 & 0  & $0 \times 0.30 = 0.00$ \\
1 & 0.42 & 1  & $1 \times 0.42 = 0.42$ \\
2 & 0.18 & 4  & $4 \times 0.18 = 0.72$ \\
3 & 0.06 & 9  & $9 \times 0.06 = 0.54$ \\
4 & 0.04 & 16 & $16 \times 0.04 = 0.64$ \\
\midrule
\textbf{Total} & \textbf{1.00} &  & \textbf{2.32} \\
\bottomrule
\end{tabular}
}
\end{table}
```
\vspace{7pt}

Hence, $E(X^2)=0+0.42+0.72+0.54+0.64=2.32$ and $Variance (X)=2.32- 1.12^2=1.0656$. Note that 1.0656 is the population variance and is very close to the sample variance (1.066) because the sample size is large.

## Exercise 2

A friend wishes to invest in one of three ordinary shares. For each company the mean and standard deviation of the annual percentage returns over the last 10 years are given below. Based on this information: \vspace{10pt}


| Name               | Mean (%) | Standard Deviation (%) |
|:-------------------|:--------:|:----------------------:|
| Peter Hugh Films   | 8        | 5                      |
| Beatrice Bakeries  | 5        | 2                      |
| Albert’s Woodcraft | 5        | 1                      |


## Exercise 2 (Cont'd)

1. Which company would you advise against? 

    . . .

    **A**: In general, there are two criteria for investment: Return and Risk (measured by standard deviation). For an individual investor, the higher return and the lower standard deviation is preferable. Hence, Beatrice Bakeries is not a suitable investment choice as it has the same mean (i.e. same return) as Albert’s Woodcraft but with a higher standard deviation. In other words, the Beatrice Bakeries is dominated by Albert’s Woodcraft.

## 

2. If your friend is very well-off and is really making the investment for ‘fun’, which would you recommend?
    
    . . .
    
    **A**: Peter Hugh Films has the highest mean of returns, but also the highest standard deviation, which makes it riskier than the other shares. Its return could well be very low or negative, or very high.

## 

3. If your friend requires a relatively secure ordinary share investment, which of these companies would you recommend?   \vspace{5pt}

    . . .
    
    \vspace{-5pt}
        
    **A**: Albert’s Woodcraft appears to be the most secure investment (less risky), due to the lowest standard deviation among the three shares.

## Exercise 3

A company is concerned about the delivery time of invoices sent through the post. It conducts a survey by telephoning a random sample of 10 customers who were sent invoices in the previous week. The following delivery times were reported (days): \vspace{5pt}

```{=latex}
\begin{center}
\centering
1 2 2 3 1 1 1 2 3 1 
\end{center}
```
\vspace{2pt}

The postal service maintains that business letters should take an average of 1.8 days with a standard deviation of 0.7 days. Based on the standard deviation and mean only do you think this sample supports this claim? (We will learn later how to perform a more structured test of whether a sample comes from a population with specific properties). 

## 

**A**:

$$
\bar{X} = 
\frac{\sum_{j=1}^{3} X_j F_j}{n}
= \frac{(1 \times 5) + (2 \times 3) + (3 \times 2)}{10}
= \frac{17}{10}
= 1.7
$$

$$
\begin{aligned}
Variance(X) &=
\frac{\sum_{j=1}^{3} (X_i - \bar{X})^2 F_j}{n - 1} \\
&= \frac{(1 - 1.7)^2 \times 5 + (2 - 1.7)^2 \times 3 + (3 - 1.7)^2 \times 2}{10 - 1} \\ 
& = \frac{2.45 + 0.27 + 3.38}{9} \\
& = 0.6777
\end{aligned}
$$

## 

$$
SD(X) = \sqrt{0.6777} = 0.823
$$

Both the estimated average (1.7) and standard deviation (0.823) of the sample do not differ much from what the postal service maintains (1.8 for average and 0.7 for standard deviation). This suggests that this specific sample can support the postal service’s claim. However, the sample size is small, and we cannot be 100% sure about this claim.

## Exercise 4

In its end of year report the Finance and Economics Faculty of a university publishes the result that 200 students obtained a degree that year. These students had an average overall percentage mark of 59%, with a standard deviation of 10%. Based on this information alone make a statement concerning: 

##

1. The number of students who obtained between 39% and 79%. 

    **A**: Mean $\mu = \bar{X} = 59\%$ and standard deviation $\sigma = S = 10\%$. According to \textbf{Chebyshev’s Inequality}, we know that $\Pr(\mu - k\sigma \le X \le \mu + k\sigma) \ge 1 - \frac{1}{k^2}$. Therefore \vspace{-7pt}
    
    $$
    \Pr(\underbrace{59 - k(10)}_{39} \le X \le \underbrace{59 + k(10)}_{79}) \ge 1 - \frac{1}{k^2}
    $$
    
    Thus, $59 - k(10) = 39 \Rightarrow k = 2$, and hence: \vspace{-7pt}
    
    $$
    \Pr(39\% \le X \le 79\%) \ge 1 - \frac{1}{2^2} = \frac{3}{4}
    $$
    
    Therefore, **at least** 150 students obtained a score between 39\% and 79\%.

## 

2. The number of students who obtained less than 39% or more than 79%. 
    
    **A**: \vspace{-12pt}
    
    $$
    \Pr(X \le 39\% \text{ or } X \ge 79\%) \le 1 - \frac{3}{4} = \frac{1}{4}
    $$
    
    Therefore, **at most** 50 students obtained less than 39\% or more than 79\%.
    
##

3. The number of students who obtained more than 89%. 

    **A**: 89% is $k = 3$ standard deviations from the mean. Hence, first consider the probability that a student receives a score between 29 and 89. \vspace{-7pt}
    
    $$
    \Pr(\underbrace{59 - k(10)}_{29} \le X \le \underbrace{59 + k(10)}_{89}) \ge 1 - \frac{1}{k^2}
    $$
    
    $$
    \Pr(29 \le X \le 89) \ge 1 - \frac{1}{3^2} = 1 - \frac{1}{9} = \frac{8}{9}
    $$
    
    Hence, a proportion of at least $1 - \frac{1}{3^2} = \frac{8}{9}$ of the students (about 178 students) obtained marks between 29\% and 89\%. As a result, a proportion of at most $\frac{1}{9}$ of the students (about 22 students) obtained a mark either more than 89\% or less than 29\%.  So, we can say that **at most** 22 students could obtain a mark more than 89\%.

## 

4. A range of marks which 50% of students attained. 

    **A**: If $1 - \frac{1}{k^2} = \frac{1}{2}$ (i.e., 50\% of students). From this example, we know that \vspace{-15pt}
    
    $$
    1 - \frac{1}{k^2} = 50\% = \frac{1}{2}
    \Rightarrow \frac{1}{k^2} = \frac{1}{2}
    \Rightarrow k^2 = 2
    \Rightarrow k = \sqrt{2} \approx 1.414
    $$
    
    As a result: \vspace{-5pt}
    
    $$
    \begin{aligned}
    & \Pr(59 - 1.414(10) \le X \le 59 + 1.414(10)) \ge 50\% \\
    & \Pr(44.86 \le X \le 73.14) \ge 50\%
    \end{aligned}
    $$
    
    
    So at least 50% of students have marks, which lie within 1.414 standard deviations of the mean (between 44.86% and 73.14%). If we need to report the intervals’ bound in the form of integer number, then we can say at least 50% of students received a mark between 44% and 74%.

## Exercise 5

It is crucial than an airline has a reputation for punctuality. The percentage of arriving flights that were punctual over a one-year period is calculated for 28 airports for two different airlines Hi-Fli and Icarus-line. By calculating suitable statistics and drawing appropriate displays of the data, compare and comment on the punctuality record of the two airlines. 

```{=latex}
\begin{table}
\centering
\tiny
\resizebox{0.65\textwidth}{!}{
\begin{tabular}{cccccc}
\toprule
\textbf{Airport} & \textbf{Hi-Fli} & \textbf{Icarus} & \textbf{Airport} & \textbf{Hi-Fli} & \textbf{Icarus} \\
\midrule
1  & 53 & 76 & 15 & 81 & 78 \\
2  & 85 & 87 & 16 & 79 & 84 \\
3  & 95 & 78 & 17 & 93 & 84 \\
4  & 82 & 77 & 18 & 69 & 85 \\
5  & 73 & 79 & 19 & 98 & 79 \\
6  & 78 & 81 & 20 & 79 & 83 \\
7  & 43 & 80 & 21 & 91 & 78 \\
8  & 77 & 81 & 22 & 69 & 82 \\
9  & 71 & 77 & 23 & 85 & 82 \\
10 & 84 & 77 & 24 & 91 & 84 \\
11 & 88 & 78 & 25 & 80 & 81 \\
12 & 78 & 80 & 26 & 98 & 81 \\
13 & 84 & 82 & 27 & 88 & 89 \\
14 & 78 & 85 & 28 & 72 & 83 \\
\bottomrule
\end{tabular}
}
\end{table}
```

##

**A**: The mean percentage of punctual flights is very similar for the two airlines: 80.1% for HI-FLI and 81.1% for ICARUS. Their medians are also close, at 80.5% and 81% respectively. 

The key difference lies in the variation. HI-FLI shows much greater variability, with punctuality ranging from 43% to 98% and a variance of 150.22. In contrast, ICARUS is far more consistent, with punctuality between 76% and 89% and a much smaller variance of 10.69. This means that while both airlines have similar average punctuality, ICARUS provides a more predictable level of performance, whereas HI-FLI’s performance is inconsistent. 

Finally, the distributions differ in shape: HI-FLI’s data are left-skewed, while ICARUS’s are right-skewed.


